services:

  db:
    image: mariadb:10.11.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db.env
    networks:
      - rezeptbuch

  redis:
    image: redis:8.2.2
    command: --appendonly yes
    volumes:
      - redisStorage:/data
    restart: always
    networks:
      - rezeptbuch

  api:
    build: ./api
    restart: always
    environment:
      - MYSQL_HOST=db
      - IMAGE_DIRECTORY=/usr/src/images
    volumes:
      - images:/usr/src/images
    env_file:
      - db.env
      - api/.env
    depends_on:
      - db
      - redis
    networks:
      - rezeptbuch

  ui:
    build: ./ui
    restart: always
    depends_on:
      - api
    env_file:
      - ui/.env
    networks:
      - rezeptbuch

  rezeptbuch:
    build: ./proxy
    container_name: rezeptbuch
    restart: always
    depends_on:
      - ui
    networks:
      - rezeptbuch
      - system-proxy_default

volumes:
  redisStorage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/niklas/rezeptbuch/db
  images:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/niklas/rezeptbuch/images

networks:
  rezeptbuch:
    driver: bridge
  system-proxy_default:
    external: true
