services:

  db:
    image: mariadb:10.11.14
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db.env

  redis:
    image: redis:8.2.2
    command: --appendonly yes
    restart: always

  api:
    build:
      context: api
      dockerfile: Dockerfile-dev
    restart: always
    environment:
      - MYSQL_HOST=db
      - IMAGE_DIRECTORY=/usr/src/images
    volumes:
      - ./api:/usr/src/app/
    env_file:
      - db.env
      - api/.env
    depends_on:
      - db
      - redis

  ui:
    build: ./ui
    restart: always
    depends_on:
      - api
    env_file:
      - ui/.env

  rezeptbuch:
    build: ./proxy
    container_name: rezeptbuch
    restart: always
    ports:
      - "3040:80"
    depends_on:
      - ui
