version: '3'

services:

  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - db.env
    networks:
      - rezeptbuch

  redis:
    image: redis
    command: --appendonly yes
    volumes:
      - redisStorage:/data
    restart: always
    networks:
      - rezeptbuch

  api:
    build: ./api
    restart: always
    environment:
      - MYSQL_HOST=db
      - IMAGE_DIRECTORY=/usr/src/images
    volumes:
      - images:/usr/src/images
    env_file:
      - db.env
      - api/.env
    depends_on:
      - db
      - redis
    networks:
      - rezeptbuch

  ui:
    build: ./ui
    restart: always
    depends_on:
      - api
    env_file:
      - ui/.env
    networks:
      - rezeptbuch

  rezeptbuch:
    build: ./proxy
    container_name: rezeptbuch
    restart: always
    depends_on:
      - ui
    networks:
      - rezeptbuch
      - system-proxy_default

volumes:
  redisStorage:
  images:

networks:
  rezeptbuch:
    driver: bridge
  system-proxy_default:
    external: true
